language: r
cache: packages
pandoc_version: 2.1.3

addons:
    apt:
        packages:
            - libopenblas-base

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install jags
  
before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh
script:
    - ./_build.sh
    - ./_deploy.sh
